In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [4]:
import numpy as np

In [5]:
np.array

<function numpy.array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0, ndmax=0, like=None)>

In [8]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [9]:
np.array([[1,2],[3,4],[5,6]])

array([[1, 2],
       [3, 4],
       [5, 6]])

In [12]:
np.array([1,2,3,4,5], dtype =float)

array([1., 2., 3., 4., 5.])

In [13]:
np.array([1,2,3], ndmin=3)

array([[[1, 2, 3]]])